### ISSUE TITLE
Can we please update the NPM version? 

### ISSUE THREAD

**Issue by martynchamberlin** [benib/aurelia-leaflet#16]
I'm noticing that [the NPM for this](https://www.npmjs.com/package/aurelia-leaflet) is very outdated and no longer compatible with the newest version of Aurelia. Can we please publish the latest version to NPM? 

Thanks!

**Comment by benib** [comment]
hi @martynchamberlin, the npm package you linked is not based on this repository but https://github.com/ceoaliongroo/aurelia-leaflet.

This is not a good situation. Also I haven't found the time to update this repo and publish it under a scope on npm.

I hope I will find the time soon to do that. If you want to install the code in this repo using npm, it should work if you install directly from github instead of npm registry. You can read the npm install docs here to see how that works: https://docs.npmjs.com/cli/install
